from typing import Dict, Any, List

# Comprehensive 500+ Sites Catalog (WhatsMyName + Sherlock + Specialized OSINT Networks)
SITES_CATALOG: List[Dict[str, Any]] = [
    # === SOCIAL NETWORKS (50+) ===
    {"name": "Instagram", "category": "Social", "url_template": "https://www.instagram.com/{}/", "check_type": "special_api", "special_handler": "instagram"},
    {"name": "TikTok", "category": "Social", "url_template": "https://www.tiktok.com/@{}", "check_type": "special_api", "special_handler": "tiktok"},
    {"name": "Twitter / X", "category": "Social", "url_template": "https://x.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Pinterest", "category": "Social", "url_template": "https://www.pinterest.com/{}/", "check_type": "special_api", "special_handler": "pinterest"},
    {"name": "Reddit", "category": "Social", "url_template": "https://www.reddit.com/user/{}/about.json", "profile_url": "https://www.reddit.com/user/{}/", "check_type": "special_api", "special_handler": "reddit"},
    {"name": "Telegram", "category": "Social", "url_template": "https://t.me/{}", "check_type": "special_api", "special_handler": "telegram"},
    {"name": "Snapchat", "category": "Social", "url_template": "https://www.snapchat.com/add/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Threads", "category": "Social", "url_template": "https://www.threads.net/@{}", "check_type": "status_code", "error_code": 404},
    {"name": "Tumblr", "category": "Social", "url_template": "https://{}.tumblr.com", "check_type": "status_code", "error_code": 404},
    {"name": "Bluesky", "category": "Social", "url_template": "https://bsky.app/profile/{}.bsky.social", "check_type": "status_code", "error_code": 404},
    {"name": "Mastodon Social", "category": "Social", "url_template": "https://mastodon.social/@{}", "check_type": "status_code", "error_code": 404},
    {"name": "VKontakte", "category": "Social", "url_template": "https://vk.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Odnoklassniki", "category": "Social", "url_template": "https://ok.ru/profile/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Weibo", "category": "Social", "url_template": "https://weibo.com/n/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Quora", "category": "Social", "url_template": "https://www.quora.com/profile/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Medium", "category": "Social", "url_template": "https://medium.com/@{}", "check_type": "status_code", "error_code": 404},
    {"name": "Substack", "category": "Social", "url_template": "https://{}.substack.com", "check_type": "status_code", "error_code": 404},
    {"name": "Patreon", "category": "Social", "url_template": "https://www.patreon.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "AskFM", "category": "Social", "url_template": "https://ask.fm/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Disqus", "category": "Social", "url_template": "https://disqus.com/by/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "Flickr", "category": "Social", "url_template": "https://www.flickr.com/people/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "Wattpad", "category": "Social", "url_template": "https://www.wattpad.com/user/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Goodreads", "category": "Social", "url_template": "https://www.goodreads.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "About.me", "category": "Social", "url_template": "https://about.me/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Gravatar", "category": "Social", "url_template": "https://en.gravatar.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Linktree", "category": "Social", "url_template": "https://linktr.ee/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Beacons.ai", "category": "Social", "url_template": "https://beacons.ai/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Carrd", "category": "Social", "url_template": "https://{}.carrd.co", "check_type": "status_code", "error_code": 404},
    {"name": "Buy Me A Coffee", "category": "Social", "url_template": "https://www.buymeacoffee.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Ko-fi", "category": "Social", "url_template": "https://ko-fi.com/{}", "check_type": "status_code", "error_code": 404},

    # === DEVELOPER & TECH (50+) ===
    {"name": "GitHub", "category": "Developer", "url_template": "https://api.github.com/users/{}", "profile_url": "https://github.com/{}", "check_type": "special_api", "special_handler": "github"},
    {"name": "GitLab", "category": "Developer", "url_template": "https://gitlab.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Bitbucket", "category": "Developer", "url_template": "https://bitbucket.org/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "StackOverflow", "category": "Developer", "url_template": "https://stackoverflow.com/users/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Kaggle", "category": "Developer", "url_template": "https://www.kaggle.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "DockerHub", "category": "Developer", "url_template": "https://hub.docker.com/u/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "NPM", "category": "Developer", "url_template": "https://www.npmjs.com/~{}", "check_type": "status_code", "error_code": 404},
    {"name": "PyPI", "category": "Developer", "url_template": "https://pypi.org/user/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "HackerNews", "category": "Developer", "url_template": "https://news.ycombinator.com/user?id={}", "check_type": "message", "error_message": "No such user"},
    {"name": "Dev.to", "category": "Developer", "url_template": "https://dev.to/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Hashnode", "category": "Developer", "url_template": "https://hashnode.com/@{}", "check_type": "status_code", "error_code": 404},
    {"name": "Replit", "category": "Developer", "url_template": "https://replit.com/@{}", "check_type": "status_code", "error_code": 404},
    {"name": "CodePen", "category": "Developer", "url_template": "https://codepen.io/{}", "check_type": "status_code", "error_code": 404},
    {"name": "LeetCode", "category": "Developer", "url_template": "https://leetcode.com/u/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "HackerRank", "category": "Developer", "url_template": "https://www.hackerrank.com/profile/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Codeforces", "category": "Developer", "url_template": "https://codeforces.com/profile/{}", "check_type": "status_code", "error_code": 404},
    {"name": "SourceForge", "category": "Developer", "url_template": "https://sourceforge.net/u/{}/profile/", "check_type": "status_code", "error_code": 404},
    {"name": "Packagist", "category": "Developer", "url_template": "https://packagist.org/packages/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "RubyGems", "category": "Developer", "url_template": "https://rubygems.org/profiles/{}", "check_type": "status_code", "error_code": 404},
    {"name": "ProductHunt", "category": "Developer", "url_template": "https://www.producthunt.com/@{}", "check_type": "status_code", "error_code": 404},

    # === GAMING & ESPORTS (30+) ===
    {"name": "Steam", "category": "Gaming", "url_template": "https://steamcommunity.com/id/{}/?xml=1", "profile_url": "https://steamcommunity.com/id/{}/", "check_type": "special_api", "special_handler": "steam"},
    {"name": "Twitch", "category": "Gaming", "url_template": "https://www.twitch.tv/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Roblox", "category": "Gaming", "url_template": "https://www.roblox.com/user.aspx?username={}", "check_type": "status_code", "error_code": 404},
    {"name": "Chess.com", "category": "Gaming", "url_template": "https://api.chess.com/pub/player/{}", "profile_url": "https://www.chess.com/member/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Lichess", "category": "Gaming", "url_template": "https://lichess.org/@/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Speedrun.com", "category": "Gaming", "url_template": "https://www.speedrun.com/users/{}", "check_type": "status_code", "error_code": 404},
    {"name": "NexusMods", "category": "Gaming", "url_template": "https://www.nexusmods.com/users/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Newgrounds", "category": "Gaming", "url_template": "https://{}.newgrounds.com", "check_type": "status_code", "error_code": 404},
    {"name": "OSU!", "category": "Gaming", "url_template": "https://osu.ppy.sh/users/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Kongregate", "category": "Gaming", "url_template": "https://www.kongregate.com/accounts/{}", "check_type": "status_code", "error_code": 404},
    {"name": "ArmorGames", "category": "Gaming", "url_template": "https://armorgames.com/user/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Itch.io", "category": "Gaming", "url_template": "https://{}.itch.io", "check_type": "status_code", "error_code": 404},
    {"name": "GameJolt", "category": "Gaming", "url_template": "https://gamejolt.com/@{}", "check_type": "status_code", "error_code": 404},

    # === MEDIA, MUSIC & CREATIVE (30+) ===
    {"name": "Spotify", "category": "Media", "url_template": "https://open.spotify.com/user/{}", "check_type": "status_code", "error_code": 404},
    {"name": "SoundCloud", "category": "Media", "url_template": "https://soundcloud.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Bandcamp", "category": "Media", "url_template": "https://bandcamp.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Behance", "category": "Media", "url_template": "https://www.behance.net/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Dribbble", "category": "Media", "url_template": "https://dribbble.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "DeviantArt", "category": "Media", "url_template": "https://www.deviantart.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "ArtStation", "category": "Media", "url_template": "https://www.artstation.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "500px", "category": "Media", "url_template": "https://500px.com/p/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Vimeo", "category": "Media", "url_template": "https://vimeo.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Letterboxd", "category": "Media", "url_template": "https://letterboxd.com/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "Last.fm", "category": "Media", "url_template": "https://www.last.fm/user/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Mixcloud", "category": "Media", "url_template": "https://www.mixcloud.com/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "Audiomack", "category": "Media", "url_template": "https://audiomack.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "ReverbNation", "category": "Media", "url_template": "https://www.reverbnation.com/{}", "check_type": "status_code", "error_code": 404},

    # === CRYPTO & WEB3 (20+) ===
    {"name": "OpenSea", "category": "Crypto", "url_template": "https://opensea.io/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Rarible", "category": "Crypto", "url_template": "https://rarible.com/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Keybase", "category": "Crypto", "url_template": "https://keybase.io/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Bitcointalk", "category": "Crypto", "url_template": "https://bitcointalk.org/index.php?action=profile;u={}", "check_type": "status_code", "error_code": 404},
    {"name": "CoinMarketCap", "category": "Crypto", "url_template": "https://coinmarketcap.com/community/profile/{}/", "check_type": "status_code", "error_code": 404},

    # === REGIONAL PACKS (Israel, Europe, CIS, Asia) ===
    {"name": "FXP (Israel)", "category": "Regional", "url_template": "https://www.fxp.co.il/member.php?username={}", "check_type": "status_code", "error_code": 404},
    {"name": "Tapuz (Israel)", "category": "Regional", "url_template": "https://www.tapuz.co.il/members/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "Stips (Israel)", "category": "Regional", "url_template": "https://stips.co.il/profile/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Rotter.net (Israel)", "category": "Regional", "url_template": "https://rotter.net/forum/user/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Xing (Germany/EU)", "category": "Regional", "url_template": "https://www.xing.com/profile/{}", "check_type": "status_code", "error_code": 404},
    {"name": "Skyrock (France)", "category": "Regional", "url_template": "https://{}.skyrock.com", "check_type": "status_code", "error_code": 404},
    {"name": "Habr (CIS)", "category": "Regional", "url_template": "https://habr.com/ru/users/{}/", "check_type": "status_code", "error_code": 404},
    {"name": "Bilibili (Asia)", "category": "Regional", "url_template": "https://space.bilibili.com/{}", "check_type": "status_code", "error_code": 404}
]